version: "3.8"
services:
  frpc_azure:
    image: ztb5129/frpc
    restart: always
    network_mode: "host"
    volumes:
      - /home/ztb5129/service/frpc_azure/config:/etc/frp
  frpc_bwg:
    image: ztb5129/frpc
    restart: always
    network_mode: "host"
    volumes:
      - /home/ztb5129/service/frpc_bwg/config:/etc/frp

