version: "3.8"
services:
  grafana:
    image: grafana/grafana
    restart: always
    user: root
    ports:
      - "3000:3000"
    volumes:
      - /home/ztb5129/service/grafana/data:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    restart: always
    user: root
    environment:
      - TZ=Asia/Shanghai
    entrypoint: /bin/prometheus
    command: >
      --config.file=/prometheus_root/config/prometheus.yml
      --web.read-timeout=5m
      --web.max-connections=10
      --storage.tsdb.retention=30d
      --storage.tsdb.path=/prometheus_root/data
      --query.max-concurrency=20
      --query.timeout=2m
    ports:
      - "9090:9090"
    volumes:
      - /home/ztb5129/service/prometheus:/prometheus_root
  watchtower:
    image: containrrr/watchtower
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=admin@redebug.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=ztb5129@live.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.exmail.qq.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=465
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=admin@redebug.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=/run/secrets/smtp_pwd
    secrets:
      - smtp_pwd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
